/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as CreateEventRouteImport } from './routes/create-event'
import { Route as BecomeOrganizerRouteImport } from './routes/become-organizer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventRoute = CreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeOrganizerRoute = BecomeOrganizerRouteImport.update({
  id: '/become-organizer',
  path: '/become-organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/create-event': typeof CreateEventRoute
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/event/$eventId': typeof EventEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/create-event': typeof CreateEventRoute
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/event/$eventId': typeof EventEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/become-organizer': typeof BecomeOrganizerRoute
  '/create-event': typeof CreateEventRoute
  '/edit-profile': typeof EditProfileRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/event/$eventId': typeof EventEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-organizer'
    | '/create-event'
    | '/edit-profile'
    | '/explore'
    | '/profile'
    | '/settings'
    | '/social'
    | '/event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/become-organizer'
    | '/create-event'
    | '/edit-profile'
    | '/explore'
    | '/profile'
    | '/settings'
    | '/social'
    | '/event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/become-organizer'
    | '/create-event'
    | '/edit-profile'
    | '/explore'
    | '/profile'
    | '/settings'
    | '/social'
    | '/event/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BecomeOrganizerRoute: typeof BecomeOrganizerRoute
  CreateEventRoute: typeof CreateEventRoute
  EditProfileRoute: typeof EditProfileRoute
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  EventEventIdRoute: typeof EventEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-event': {
      id: '/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof CreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-organizer': {
      id: '/become-organizer'
      path: '/become-organizer'
      fullPath: '/become-organizer'
      preLoaderRoute: typeof BecomeOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BecomeOrganizerRoute: BecomeOrganizerRoute,
  CreateEventRoute: CreateEventRoute,
  EditProfileRoute: EditProfileRoute,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  EventEventIdRoute: EventEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
